ALTER TABLE partners
    ADD COLUMN trade_name VARCHAR(200) NOT NULL DEFAULT '' AFTER phone,
    ADD COLUMN contact_person VARCHAR(150) NOT NULL DEFAULT '' AFTER trade_name,
    ADD COLUMN mobile VARCHAR(20) NOT NULL DEFAULT '' AFTER contact_person,
    ADD COLUMN website VARCHAR(255) NOT NULL DEFAULT '' AFTER mobile,
    ADD COLUMN customer_code VARCHAR(50) NOT NULL DEFAULT '' AFTER website,
    ADD COLUMN supplier_code VARCHAR(50) NOT NULL DEFAULT '' AFTER customer_code,
    ADD COLUMN relationship_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' AFTER supplier_code,
    ADD COLUMN relationship_since DATE NULL AFTER relationship_status,
    ADD COLUMN sales_representative VARCHAR(150) NOT NULL DEFAULT '' AFTER relationship_since,
    ADD COLUMN price_list VARCHAR(100) NOT NULL DEFAULT '' AFTER sales_representative,
    ADD COLUMN default_discount DECIMAL(8,2) NOT NULL DEFAULT 0 AFTER price_list,
    ADD COLUMN credit_limit DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER default_discount,
    ADD COLUMN payment_day INT NOT NULL DEFAULT 0 AFTER credit_limit,
    ADD COLUMN customer_account VARCHAR(20) NOT NULL DEFAULT '' AFTER payment_day,
    ADD COLUMN supplier_account VARCHAR(20) NOT NULL DEFAULT '' AFTER customer_account,
    ADD COLUMN bank_name VARCHAR(150) NOT NULL DEFAULT '' AFTER supplier_account,
    ADD COLUMN bank_account_holder VARCHAR(200) NOT NULL DEFAULT '' AFTER bank_name,
    ADD COLUMN swift_bic VARCHAR(11) NOT NULL DEFAULT '' AFTER bank_account_holder,
    ADD COLUMN contract_summary TEXT NOT NULL AFTER swift_bic,
    ADD COLUMN accrual_notes TEXT NOT NULL AFTER contract_summary,
    ADD COLUMN internal_notes TEXT NOT NULL AFTER accrual_notes,
    ADD CONSTRAINT chk_partners_payment_day CHECK (payment_day >= 0 AND payment_day <= 31),
    ADD CONSTRAINT chk_partners_default_discount CHECK (default_discount >= 0 AND default_discount <= 100),
    ADD CONSTRAINT chk_partners_credit_limit CHECK (credit_limit >= 0);
