package cat.contacat.erp.core.partner.api;

import cat.contacat.erp.core.partner.Partner;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;

public record PartnerResponse(
    String id,
    String companyId,
    String name,
    String taxId,
    String email,
    String phone,
    String tradeName,
    String contactPerson,
    String mobile,
    String website,
    String customerCode,
    String supplierCode,
    String relationshipStatus,
    LocalDate relationshipSince,
    String salesRepresentative,
    String priceList,
    BigDecimal defaultDiscount,
    BigDecimal creditLimit,
    int paymentDay,
    String customerAccount,
    String supplierAccount,
    String bankName,
    String bankAccountHolder,
    String swiftBic,
    String contractSummary,
    String accrualNotes,
    String internalNotes,
    boolean supplier,
    boolean customer,
    String documentType,
    String addressStreet,
    String addressNumber,
    String addressFloor,
    String postalCode,
    String city,
    String province,
    String country,
    String vatRegime,
    boolean intraEu,
    String euVatNumber,
    String iban,
    String paymentMethod,
    int paymentDays,
    boolean active,
    OffsetDateTime createdAt,
    OffsetDateTime updatedAt
) {

    public static PartnerResponse from(Partner partner) {
        return new PartnerResponse(
            partner.getId(),
            partner.getCompany().getId(),
            partner.getName(),
            partner.getTaxId(),
            partner.getEmail(),
            partner.getPhone(),
            partner.getTradeName(),
            partner.getContactPerson(),
            partner.getMobile(),
            partner.getWebsite(),
            partner.getCustomerCode(),
            partner.getSupplierCode(),
            partner.getRelationshipStatus(),
            partner.getRelationshipSince(),
            partner.getSalesRepresentative(),
            partner.getPriceList(),
            partner.getDefaultDiscount(),
            partner.getCreditLimit(),
            partner.getPaymentDay(),
            partner.getCustomerAccount(),
            partner.getSupplierAccount(),
            partner.getBankName(),
            partner.getBankAccountHolder(),
            partner.getSwiftBic(),
            partner.getContractSummary(),
            partner.getAccrualNotes(),
            partner.getInternalNotes(),
            partner.isSupplier(),
            partner.isCustomer(),
            partner.getDocumentType(),
            partner.getAddressStreet(),
            partner.getAddressNumber(),
            partner.getAddressFloor(),
            partner.getPostalCode(),
            partner.getCity(),
            partner.getProvince(),
            partner.getCountry(),
            partner.getVatRegime(),
            partner.isIntraEu(),
            partner.getEuVatNumber(),
            partner.getIban(),
            partner.getPaymentMethod(),
            partner.getPaymentDays(),
            partner.isActive(),
            partner.getCreatedAt(),
            partner.getUpdatedAt()
        );
    }
}
